add --sinceDate=yyyy/mm/dd option to filter downloaded photos by date
mohsen1/fb-photo-fetch pull request #5
Opened 2016-12-17 21:22 UTC by wehrwein1

2016-12-17 21:51 UTC, mohsen1 requested changes
Do Date.parse outside of the filter function and safely fall back to 0 when parse fails.

2016-12-18 17:11 UTC, wehrwein1 commented
Done. Pulled in 'moment' to handle the date parsing and isValid() date check.

2016-12-18 18:25 UTC, mohsen1 approved these changes

2016-12-18 18:25 UTC, merged

2016-12-18 18:34 UTC, wehrwein1 commented
Great, thanks! I think that'll do it from me.